### ISSUE TITLE
Dice score coefficient

### ISSUE THREAD

**Issue by rtan265** [jaeho3690/LIDC-IDRI-Segmentation#6]
Hi Jaeho, 

I was wondering what results you were able to get with your segmentation model? Specifically UNET (with and without augmentation).
Please let me know!

**Comment by shahenda-mahmoud-mabrouk-saed** [comment]
Hi Jaeho,
It's a very nice repository for segmentation model. I'm using your repository for segmenting the data of LIDC-IDRI but I'm facing the following error while running your codes as per your directions:
![image](https://user-images.githubusercontent.com/48654031/118540507-502c8780-b759-11eb-98e1-da4acbf0e56e.png)

Can you please help, what could be the probable solution.
Thanks.

**Comment by jaeho3690** [comment]
Hi Ryan,

Sorry for the late reply. I didn't know there was an issue. The DICE score for UNET without augmentation was around 
 0.58 to 0.6, and augmentation only improved the score by 0.01 to 0.03.
