### ISSUE TITLE
CUDA Memory Error

### ISSUE THREAD

**Issue by shahenda-mahmoud-mabrouk-saed** [jaeho3690/LIDC-IDRI-Segmentation#7]
Hi Jaeho,
It's a very nice repository for segmentation model. I'm using your repository for segmenting the data of LIDC-IDRI but I'm facing the following error while running your codes as per your directions: 
![image](https://user-images.githubusercontent.com/48654031/118545807-c3d19300-b75f-11eb-8193-0eaa5eb5f20a.png)

I'm using NVIDIA Geforce 940MX GPU with cuda, pytorch installed in virtual env. 
Can you please help, what could be the probable solution.
Thanks.

**Comment by jaeho3690** [comment]
Hi, it seems that your GPU has a small memory size to handle this data. Try reducing the batch size.
Or you might have to resize the image for memory. This, of course, means that you have to adjust the whole architecture as well.
